#!/usr/bin/env bash
# This acheives same as task 0 but service (init) must say that nginx is not running 
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
