#!/usr/bin/env bash
# This script displays a list of currently running processes in a user-oriented format.

# Use the ps command to list all processes, showing user-oriented information
ps aux --forest | head -50
